"""empty message

Revision ID: 54f140b8f5de
Revises: 756f9a9e3578
Create Date: 2017-03-05 18:14:29.883391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f140b8f5de'
down_revision = '756f9a9e3578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('domain', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
