"""empty message

Revision ID: 756f9a9e3578
Revises: ac5cb2a52c53
Create Date: 2017-03-05 18:06:38.660271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756f9a9e3578'
down_revision = 'ac5cb2a52c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('bias', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    # ### end Alembic commands ###
