"""empty message

Revision ID: bf3afea0edc7
Revises: 
Create Date: 2017-03-05 13:46:05.817436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3afea0edc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('bias', sa.String(length=64), nullable=True),
    sa.Column('publishedDate', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('authors', sa.String(length=256), nullable=True),
    sa.Column('keywords', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('googleID', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('googleID')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('visits',
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('timeIn', sa.DateTime(), nullable=False),
    sa.Column('timeOut', sa.DateTime(), nullable=True),
    sa.Column('timeSpent', sa.Float(), nullable=True),
    sa.Column('receivedSuggestions', sa.Boolean(), nullable=True),
    sa.Column('clickedSuggestion', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userID', 'timeIn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('articles')
    # ### end Alembic commands ###
