"""empty message

Revision ID: c0679bf26cde
Revises: 9ba200a66cba
Create Date: 2017-02-06 15:40:10.266417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0679bf26cde'
down_revision = '9ba200a66cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('bias', sa.String(length=64), nullable=True),
    sa.Column('publishedDate', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('authors', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source', 'title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
