"""empty message

Revision ID: e3285037f271
Revises: 54f140b8f5de
Create Date: 2017-03-05 19:25:06.725128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3285037f271'
down_revision = '54f140b8f5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('allSidesURL', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'allSidesURL')
    # ### end Alembic commands ###
